name: startup_namer
description: A startup-namer app.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

# #docregion dependencies
dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+2
# #enddocregion dependencies

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true